version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/dotnet"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "bundler"
    directory: "/ruby"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "mix"
    directory: "/elixir"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "swift"
    directory: "/swift"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
