package md.remit;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import md.remit.internal.ApiClient;
import md.remit.signer.PrivateKeySigner;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

import java.io.File;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.DynamicTest.dynamicTest;

/**
 * Golden vector tests: Java SDK must reproduce the server's EIP-712 hashes exactly.
 *
 * Loads test-vectors/eip712.json (generated by `cargo run --bin gen_vectors` in remit-server)
 * and verifies that ApiClient.computeEip712Hash produces the same hash for each vector.
 * Also verifies the ECDSA signature matches when signing with the same key.
 *
 * If any assertion fails, the Java SDK's EIP-712 implementation diverges from the
 * server and authentication WILL fail in production.
 */
@DisplayName("Golden vector tests: EIP-712 hash and signature")
class GoldenVectorTest {

    // Anvil test wallet #0 - same key used by gen_vectors in remit-server.
    private static final String TEST_PRIV_KEY =
        "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

    record VectorData(
        String description,
        long chainId,
        String verifyingContract,
        String method,
        String path,
        long timestamp,   // Java long bit-pattern matching u64 (may be negative for > Long.MAX_VALUE)
        byte[] nonce,
        String expectedHash,
        String expectedSignature
    ) {}

    private static List<VectorData> vectors;

    @BeforeAll
    static void loadVectors() throws Exception {
        File f = Paths.get("../test-vectors/eip712.json").toFile();
        assertThat(f).as("test-vectors/eip712.json - run `cargo run --bin gen_vectors` first")
            .exists();
        JsonNode root = new ObjectMapper().readTree(f);
        JsonNode arr = root.get("vectors");
        assertThat(arr.size()).as("vectors array must not be empty").isGreaterThan(0);

        vectors = new ArrayList<>();
        for (JsonNode v : arr) {
            JsonNode dom = v.get("domain");
            JsonNode msg = v.get("message");

            // Parse timestamp as text to avoid IEEE 754 precision loss for u64::MAX.
            // Long.parseUnsignedLong handles values > Long.MAX_VALUE (stored as negative bits).
            long timestamp = Long.parseUnsignedLong(msg.get("timestamp").asText());

            String nonceHex = msg.get("nonce").asText();
            byte[] nonce = parseNonce(nonceHex);

            vectors.add(new VectorData(
                v.get("description").asText(),
                dom.get("chain_id").asLong(),
                dom.get("verifying_contract").asText(),
                msg.get("method").asText(),
                msg.get("path").asText(),
                timestamp,
                nonce,
                v.get("expected_hash").asText(),
                v.get("expected_signature").asText()
            ));
        }
    }

    // ─── Tests ────────────────────────────────────────────────────────────────

    @TestFactory
    @DisplayName("EIP-712 hash matches server")
    Stream<DynamicTest> goldenVectorsHash() {
        return vectors.stream().map(v -> dynamicTest(v.description(), () -> {
            byte[] gotHash = ApiClient.computeEip712Hash(
                v.chainId(),
                v.verifyingContract(),
                v.method(),
                v.path(),
                v.timestamp(),
                v.nonce()
            );
            String gotHex = "0x" + HexFormat.of().formatHex(gotHash);
            assertThat(gotHex)
                .as("EIP-712 hash mismatch for '%s'", v.description())
                .isEqualTo(v.expectedHash());
        }));
    }

    @TestFactory
    @DisplayName("Signature matches server")
    Stream<DynamicTest> goldenVectorsSignature() throws Exception {
        PrivateKeySigner signer = new PrivateKeySigner(TEST_PRIV_KEY);
        return vectors.stream().map(v -> dynamicTest(v.description(), () -> {
            byte[] digest = ApiClient.computeEip712Hash(
                v.chainId(),
                v.verifyingContract(),
                v.method(),
                v.path(),
                v.timestamp(),
                v.nonce()
            );
            byte[] sig = signer.sign(digest);
            String gotSig = "0x" + HexFormat.of().formatHex(sig);
            assertThat(gotSig)
                .as("Signature mismatch for '%s'", v.description())
                .isEqualTo(v.expectedSignature());
        }));
    }

    // ─── Helpers ──────────────────────────────────────────────────────────────

    private static byte[] parseNonce(String s) {
        String hex = s.startsWith("0x") ? s.substring(2) : s;
        byte[] b = HexFormat.of().parseHex(hex);
        assertThat(b).as("nonce must be 32 bytes").hasSize(32);
        return b;
    }
}
