# frozen_string_literal: true

require "spec_helper"
require "json"

# Golden vector tests: Ruby SDK must reproduce the server's EIP-712 hashes exactly.
#
# Loads test-vectors/eip712.json (generated by `cargo run --bin gen_vectors` in remit-server)
# and verifies that the EIP-712 hash and signature match for each vector.
#
# If any assertion fails, the Ruby SDK's EIP-712 implementation diverges from the
# server and authentication WILL fail in production.

VECTORS_PATH = File.expand_path("../../test-vectors/eip712.json", __dir__)

# Anvil test wallet #0 — same key used by gen_vectors in remit-server.
TEST_PRIV_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

def load_vectors
  unless File.exist?(VECTORS_PATH)
    skip "test-vectors/eip712.json not found — run gen_vectors"
  end

  file = JSON.parse(File.read(VECTORS_PATH))
  vectors = file["vectors"]
  raise "vectors array must not be empty" if vectors.empty?
  vectors
end

# Build a test transport that exposes eip712_hash and signer for testing.
class TestTransport < Remitmd::HttpTransport
  def compute_eip712_hash(method, path, timestamp, nonce_bytes)
    eip712_hash(method, path, timestamp, nonce_bytes)
  end
end

RSpec.describe "Golden vectors: EIP-712 hash matches server" do
  let(:vectors) { load_vectors }

  it "loads at least one vector" do
    expect(vectors.length).to be > 0
  end

  it "EIP-712 hash matches for all vectors" do
    signer    = Remitmd::PrivateKeySigner.new(TEST_PRIV_KEY)
    transport = TestTransport.new(
      base_url:       "https://testnet.remit.md",
      signer:         signer,
      chain_id:       84532,
      router_address: ""
    )

    vectors.each do |v|
      nonce_hex   = v.dig("message", "nonce")
      nonce_bytes = [nonce_hex.delete_prefix("0x")].pack("H*")
      expect(nonce_bytes.bytesize).to eq(32), "nonce must be 32 bytes for: #{v["description"]}"

      # Parse timestamp carefully — must preserve u64::MAX without float precision loss.
      timestamp = Integer(v.dig("message", "timestamp").to_s)

      chain_id = v.dig("domain", "chain_id")
      router   = v.dig("domain", "verifying_contract")

      # Temporarily patch chain_id and router_address for this test.
      transport.instance_variable_set(:@chain_id, chain_id)
      transport.instance_variable_set(:@router_address, router)

      got_hash = transport.compute_eip712_hash(
        v.dig("message", "method"),
        v.dig("message", "path"),
        timestamp,
        nonce_bytes
      )
      got_hex = "0x#{got_hash.unpack1("H*")}"

      expect(got_hex).to eq(v["expected_hash"]),
        "EIP-712 hash mismatch for '#{v["description"]}'"
    end
  end
end

RSpec.describe "Golden vectors: signature matches server" do
  let(:vectors) { load_vectors }
  let(:signer)  { Remitmd::PrivateKeySigner.new(TEST_PRIV_KEY) }

  it "ECDSA signature matches for all vectors" do
    transport = TestTransport.new(
      base_url:       "https://testnet.remit.md",
      signer:         signer,
      chain_id:       84532,
      router_address: ""
    )

    vectors.each do |v|
      nonce_hex   = v.dig("message", "nonce")
      nonce_bytes = [nonce_hex.delete_prefix("0x")].pack("H*")
      timestamp   = Integer(v.dig("message", "timestamp").to_s)
      chain_id    = v.dig("domain", "chain_id")
      router      = v.dig("domain", "verifying_contract")

      transport.instance_variable_set(:@chain_id, chain_id)
      transport.instance_variable_set(:@router_address, router)

      digest = transport.compute_eip712_hash(
        v.dig("message", "method"),
        v.dig("message", "path"),
        timestamp,
        nonce_bytes
      )
      got_sig = signer.sign(digest)

      expect(got_sig).to eq(v["expected_signature"]),
        "Signature mismatch for '#{v["description"]}'"
    end
  end
end
