/**
 * Golden vector tests: TypeScript SDK must reproduce the server's EIP-712 hashes exactly.
 *
 * Loads test-vectors/eip712.json (generated by `cargo run --bin gen_vectors` in remit-server)
 * and verifies that viem's hashTypedData produces the same EIP-712 hash for each vector.
 * Also verifies the ECDSA signature matches when signing with the same key.
 *
 * If any assertion fails, the TypeScript SDK's EIP-712 implementation diverges from the
 * server and authentication WILL fail in production.
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { hashTypedData } from "viem";
import { privateKeyToAccount } from "viem/accounts";

// ─── Test fixtures ────────────────────────────────────────────────────────────

const __dirname = dirname(fileURLToPath(import.meta.url));
const VECTORS_PATH = join(__dirname, "../../test-vectors/eip712.json");

// Anvil test wallet #0 - same key used by gen_vectors in remit-server.
const TEST_PRIVATE_KEY =
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" as const;

// EIP-712 typed struct - must match server's auth.rs exactly.
const EIP712_TYPES = {
  APIRequest: [
    { name: "method", type: "string" },
    { name: "path", type: "string" },
    { name: "timestamp", type: "uint256" },
    { name: "nonce", type: "bytes32" },
  ],
} as const;

interface VectorDomain {
  name: string;
  version: string;
  chain_id: number;
  verifying_contract: string;
}

interface VectorMessage {
  method: string;
  path: string;
  timestamp: number;
  nonce: string;
}

interface Vector {
  description: string;
  domain: VectorDomain;
  message: VectorMessage;
  signer: string;
  expected_domain_separator: string;
  expected_struct_hash: string;
  expected_hash: string;
  expected_signature: string;
}

interface VectorFile {
  version: string;
  vectors: Vector[];
}

interface VectorWithBigint extends Vector {
  /** Timestamp as BigInt - JSON.parse loses precision for u64::MAX in JS. */
  timestampBigint: bigint;
}

function loadVectors(): VectorWithBigint[] {
  const raw = readFileSync(VECTORS_PATH, "utf8");
  const file = JSON.parse(raw) as VectorFile;
  assert.ok(file.vectors.length > 0, "vectors array must not be empty");

  // Extract timestamps as exact BigInts from the raw JSON string to avoid
  // IEEE 754 precision loss for very large values (e.g. u64::MAX).
  const timestampMatches = [...raw.matchAll(/"timestamp":\s*(\d+)/g)];
  assert.equal(
    timestampMatches.length,
    file.vectors.length,
    "Each vector must have exactly one timestamp field",
  );

  return file.vectors.map((v, i) => ({
    ...v,
    timestampBigint: BigInt(timestampMatches[i]![1]),
  }));
}

const vectors: VectorWithBigint[] = loadVectors();

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("Golden vector: EIP-712 hash matches server", () => {
  for (const vector of vectors) {
    it(vector.description, () => {
      const domain = {
        name: vector.domain.name,
        version: vector.domain.version,
        chainId: vector.domain.chain_id,
        verifyingContract: vector.domain.verifying_contract as `0x${string}`,
      };
      const message = {
        method: vector.message.method,
        path: vector.message.path,
        timestamp: vector.timestampBigint,
        nonce: vector.message.nonce as `0x${string}`,
      };

      const gotHash = hashTypedData({
        domain,
        types: EIP712_TYPES,
        primaryType: "APIRequest",
        message,
      });

      assert.equal(
        gotHash,
        vector.expected_hash,
        `EIP-712 hash mismatch for '${vector.description}'`,
      );
    });
  }
});

describe("Golden vector: signature matches server", () => {
  const account = privateKeyToAccount(TEST_PRIVATE_KEY);

  for (const vector of vectors) {
    it(vector.description, async () => {
      const domain = {
        name: vector.domain.name,
        version: vector.domain.version,
        chainId: vector.domain.chain_id,
        verifyingContract: vector.domain.verifying_contract as `0x${string}`,
      };
      const message = {
        method: vector.message.method,
        path: vector.message.path,
        timestamp: vector.timestampBigint,
        nonce: vector.message.nonce as `0x${string}`,
      };

      const gotSig = await account.signTypedData({
        domain,
        types: EIP712_TYPES,
        primaryType: "APIRequest",
        message,
      });

      assert.equal(
        gotSig,
        vector.expected_signature,
        `Signature mismatch for '${vector.description}'`,
      );
    });
  }
});
