using System.Text.Json;
using System.Text.Json.Nodes;
using RemitMd;
using Xunit;

namespace RemitMd.Tests;

/// <summary>
/// Golden vector tests: .NET SDK must reproduce the server's EIP-712 hashes exactly.
///
/// Loads test-vectors/eip712.json (generated by `cargo run --bin gen_vectors` in remit-server)
/// and verifies that Eip712.ComputeRequestDigest produces the same hash for each vector.
/// Also verifies the ECDSA signature matches when signing with the same key.
///
/// If any assertion fails, the .NET SDK's EIP-712 implementation diverges from the
/// server and authentication WILL fail in production.
/// </summary>
public sealed class GoldenVectorTests
{
    // Anvil test wallet #0 — same key used by gen_vectors in remit-server.
    private const string TestPrivKey =
        "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

    private static readonly string VectorsPath =
        Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../..", "test-vectors", "eip712.json"));

    public record VectorData(
        string Description,
        long ChainId,
        string VerifyingContract,
        string Method,
        string Path,
        ulong Timestamp,
        byte[] Nonce,
        string ExpectedHash,
        string ExpectedSignature);

    private static List<VectorData> LoadVectors()
    {
        Assert.True(File.Exists(VectorsPath),
            $"test-vectors/eip712.json not found at {VectorsPath}. " +
            "Run `cargo run --bin gen_vectors` in remit-server first.");

        var json = File.ReadAllText(VectorsPath);
        var root = JsonNode.Parse(json)!;
        var arr  = root["vectors"]!.AsArray();
        Assert.NotEmpty(arr);

        var result = new List<VectorData>();
        foreach (var v in arr)
        {
            var dom = v!["domain"]!;
            var msg = v["message"]!;

            // Parse timestamp as a string to avoid ulong overflow issues with JSON parsing.
            var tsText  = msg["timestamp"]!.ToString();
            var timestamp = ulong.Parse(tsText);

            var nonceHex = msg["nonce"]!.GetValue<string>();
            var nonce = ParseNonce(nonceHex);

            result.Add(new VectorData(
                v["description"]!.GetValue<string>(),
                dom["chain_id"]!.GetValue<long>(),
                dom["verifying_contract"]!.GetValue<string>(),
                msg["method"]!.GetValue<string>(),
                msg["path"]!.GetValue<string>(),
                timestamp,
                nonce,
                v["expected_hash"]!.GetValue<string>(),
                v["expected_signature"]!.GetValue<string>()
            ));
        }
        return result;
    }

    public static IEnumerable<object[]> Vectors() =>
        LoadVectors().Select(v => new object[] { v });

    [Theory]
    [MemberData(nameof(Vectors))]
    public void EIP712Hash_MatchesServer(VectorData v)
    {
        var digest = Eip712.ComputeRequestDigest(
            v.ChainId, v.VerifyingContract, v.Method, v.Path, v.Timestamp, v.Nonce);
        var gotHex = "0x" + Convert.ToHexString(digest).ToLowerInvariant();
        Assert.Equal(v.ExpectedHash, gotHex);
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public void Signature_MatchesServer(VectorData v)
    {
        var signer = new PrivateKeySigner(TestPrivKey);
        var digest  = Eip712.ComputeRequestDigest(
            v.ChainId, v.VerifyingContract, v.Method, v.Path, v.Timestamp, v.Nonce);
        var gotSig = signer.Sign(digest);
        Assert.Equal(v.ExpectedSignature, gotSig);
    }

    private static byte[] ParseNonce(string hex)
    {
        var clean = hex.StartsWith("0x", StringComparison.OrdinalIgnoreCase) ? hex[2..] : hex;
        Assert.Equal(64, clean.Length); // must be 32 bytes
        return Convert.FromHexString(clean);
    }
}
